import { useMemo } from 'react';
import { ArrowUpRight, Crosshair, Info } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { radialProbabilityCurve } from '../physics/calculations/radialProbability.js';

export default function ProbabilityPanel({ radiusA0, probability }) {
  const data = useMemo(() => radialProbabilityCurve(180, 8), []);
  return <>
    <section className="panel probability-panel"><div className="panel-heading"><span className="icon-box green"><Crosshair size={16}/></span><div><div className="eyebrow">ENCLOSED REGION</div><h2>Probability within R</h2></div></div><div className="probability-value">{(probability * 100).toFixed(2)}<span>%</span></div><div className="probability-sub">electron found inside <b>r ≤ {radiusA0.toFixed(1)} a₀</b></div><div className="probability-track"><div style={{width:`${probability*100}%`}}/></div><div className="probability-foot"><span>0%</span><span>100%</span></div><p className="equation">P(r ≤ R) = 1 − e<sup>−2R/a₀</sup>(1 + 2R/a₀ + 2R²/a₀²)</p></section>
    <section className="panel chart-panel"><div className="panel-heading chart-heading"><div><div className="eyebrow">RADIAL DISTRIBUTION</div><h2>Probability by radius</h2></div><span className="units">per a₀</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:8,right:8,left:-22,bottom:0}}><defs><linearGradient id="radialFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#55c8ec" stopOpacity={0.3}/><stop offset="100%" stopColor="#55c8ec" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid stroke="#ffffff0b" vertical={false}/><XAxis dataKey="radiusA0" type="number" domain={[0,8]} ticks={[0,2,4,6,8]} stroke="#576575" tickLine={false} axisLine={false} tick={{fill:'#8290a0',fontSize:10}}/><YAxis stroke="#576575" tickLine={false} axisLine={false} tick={{fill:'#8290a0',fontSize:10}}/><Tooltip contentStyle={{background:'#111923',border:'1px solid #283747',borderRadius:8,color:'#eaf2f8'}} formatter={(v)=>[Number(v).toFixed(4),'density / a₀'] } labelFormatter={(v)=>`${Number(v).toFixed(2)} a₀`}/><Area type="monotone" dataKey="probabilityPerA0" stroke="#65d1f1" strokeWidth={2} fill="url(#radialFill)"/><ReferenceLine x={1} stroke="#e7ba72" strokeDasharray="4 4"/><ReferenceLine x={radiusA0} stroke="#b7d98e" strokeDasharray="3 4"/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="legend-blue"/> Radial probability</span><span><i className="legend-gold"/> a₀ reference</span><span><i className="legend-green"/> Selected radius</span></div></section>
    <section className="panel info-panel"><div className="panel-heading"><span className="icon-box"><Info size={16}/></span><div><div className="eyebrow">ABOUT THIS STATE</div><h2>Hydrogen · 1s</h2></div><ArrowUpRight className="heading-end" size={16}/></div><p>The wavefunction ψ describes the quantum state. Its squared magnitude, |ψ|², is the probability density per unit volume.</p><p>The radial distribution <b>4πr²|ψ|²</b> gives probability per unit radius. The point cloud samples electron positions from this distribution and is diffuse because the 1s state is spherically symmetric.</p><p className="info-note">An electron in a stationary orbital is not a classical particle circling the nucleus. The cloud visualizes measurement probabilities, not matter or a path.</p></section>
  </>;
}
